package sugarcube.jexter.write;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType0Font;
import org.apache.pdfbox.pdmodel.graphics.blend.BlendMode;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.apache.pdfbox.pdmodel.graphics.shading.PDShading;
import org.apache.pdfbox.pdmodel.graphics.state.RenderingMode;
import org.apache.pdfbox.pdmodel.graphics.state.PDExtendedGraphicsState;
import org.apache.pdfbox.util.Matrix;
import org.apache.pdfbox.cos.COSArray;
import org.apache.pdfbox.cos.COSBoolean;
import org.apache.pdfbox.cos.COSDictionary;
import org.apache.pdfbox.cos.COSFloat;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.pdmodel.interactive.documentnavigation.outline.PDDocumentOutline;
import org.apache.pdfbox.pdmodel.interactive.documentnavigation.outline.PDOutlineItem;
import org.apache.pdfbox.pdmodel.interactive.documentnavigation.destination.PDPageFitWidthDestination;

import sugarcube.jexter.convert.ConvertOptions;
import sugarcube.jexter.core.JxLog;
import sugarcube.jexter.core.JxPath;
import sugarcube.jexter.core.JxRect;
import sugarcube.jexter.core.JxTransform;
import sugarcube.jexter.font.JxFont;
import sugarcube.jexter.ocd.model.OCDClip;
import sugarcube.jexter.ocd.model.OCDDocument;
import sugarcube.jexter.ocd.model.OCDFont;
import sugarcube.jexter.ocd.model.OCDGlyph;
import sugarcube.jexter.ocd.model.OCDGradient;
import sugarcube.jexter.ocd.model.OCDGroup;
import sugarcube.jexter.ocd.model.OCDImage;
import sugarcube.jexter.ocd.model.OCDMedia;
import sugarcube.jexter.ocd.model.OCDNode;
import sugarcube.jexter.ocd.model.OCDPage;
import sugarcube.jexter.ocd.model.OCDPath;
import sugarcube.jexter.ocd.model.OCDText;
import sugarcube.jexter.ocd.model.OCDStruct;

import java.awt.geom.AffineTransform;
import java.awt.geom.PathIterator;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import java.util.Deque;
import java.util.ArrayDeque;

/**
 * Writes an {@link OCDDocument} as a PDF via PDFBox content streams, in one of
 * two text modes:
 *
 * <ul>
 *   <li><b>outline</b> (default) — text is drawn as filled glyph outlines:
 *       pixel-exact, but not selectable/searchable.</li>
 *   <li><b>selectable</b> — each run's font is embedded as a {@link PDType0Font}
 *       (compiled from the OCD glyph outlines by {@link JxFont#toOtf}), and
 *       glyphs are shown with {@code showText} so the text is selectable and
 *       searchable, with a ToUnicode CMap generated by PDFBox. Each glyph is
 *       placed by its own text matrix (baseline · translate(x,0)), so positions
 *       stay pixel-exact instead of relying on the font's advance widths.
 *       Glyphs with no encodable unicode fall back to an outline fill.</li>
 * </ul>
 *
 * <p>PDF user space is Y-up, the same as OCD page space, so page-space path
 * geometry maps directly with no flip; text/image nodes carry their own
 * transform. Per-node clip and fill/stroke alpha + blend (via ExtGState) are
 * applied inside a q…Q pair so they don't leak.
 */
public final class PdfWriter {

    private final PDDocument pdf;
    private final boolean selectable;
    private final Map<String, PDFont> fonts = new HashMap<>();
    private final Map<String, PDImageXObject> images = new HashMap<>();

    private PdfWriter(PDDocument pdf, boolean selectable) { this.pdf = pdf; this.selectable = selectable; }

    /** Uniform projection. {@link ConvertOptions#SELECTABLE} = embed fonts and place real,
     *  copyable text; otherwise a pixel-exact outline facsimile (text not selectable). */
    public static void write(OCDDocument doc, OutputStream out, ConvertOptions opt) throws IOException {
        try (PDDocument pdf = new PDDocument()) {
            PdfWriter w = new PdfWriter(pdf, opt.get(ConvertOptions.SELECTABLE));
            for (OCDPage p : doc.pages()) w.page(doc, p);
            outline(pdf, doc);                       // navigable bookmarks from the heading structure
            stamp(pdf, doc);                         // deterministic CreationDate + trailer /ID
            pdf.save(out);
        }
    }

    private void page(OCDDocument doc, OCDPage p) throws IOException {
        JxRect box = p.effectiveBox();
        // The page box KEEPS its origin. Model coordinates are media-absolute, so a CropBox that does
        // not start at (0,0) — a trimmed page, very common in print-ready books — must be re-stated as
        // a box at that same origin. Building PDRectangle(w, h) instead put the page at (0,0) while the
        // content stayed at media coordinates, shifting every node by the crop origin: measured 28.35 pt
        // on a real 600-page book, a visibly displaced cover, and 1.9% of pixels on the synthetic
        // page_mediabox_cropbox feature. Invisible to every container gate — only a pixel compare
        // against PDFBox sees it.
        PDPage page = new PDPage(new PDRectangle((float) box.minX(), (float) box.minY(),
                                                 (float) box.width(), (float) box.height()));
        if (p.rotation() != 0) page.setRotation(p.rotation());   // content stays in unrotated user space
        pdf.addPage(page);
        try (PDPageContentStream cs = new PDPageContentStream(pdf, page)) {
            for (OCDNode n : OCDNode.inPaintOrder(p.content())) paint(cs, n, doc, p);
        }
    }

    private void paint(PDPageContentStream cs, OCDNode n, OCDDocument doc, OCDPage page) throws IOException {
        cs.saveGraphicsState();
        try {
            if (n.hasClip()) {
                OCDClip c = page.clip(n.clipId());
                if (c != null && c.path() != null) {
                    emitGeom(cs, c.path());
                    if (c.path().isEvenOdd()) cs.clipEvenOdd(); else cs.clip();
                }
            }
            applyState(cs, n);
            switch (n) {
                case OCDPath p   -> paintPath(cs, p);
                case OCDText t   -> { if (selectable) paintTextEmbedded(cs, t, doc); else paintTextOutline(cs, t, doc); }
                case OCDImage im -> paintImage(cs, im, doc);
                case OCDMedia m  -> { /* media has no PDF re-export representation */ }
                case OCDGroup g  -> {
                    // A read-back group carries its own transform (the importer flattens, the
                    // reader preserves) — push it around the children or every grouped mark
                    // paints unscaled at the origin. q/Q come from the enclosing save/restore.
                    if (g.transform() != null && !g.transform().isIdentity())
                        cs.transform(new org.apache.pdfbox.util.Matrix(g.transform().awt()));
                    for (OCDNode c : OCDNode.inPaintOrder(g.children())) paint(cs, c, doc, page);
                }
                default -> { }
            }
        } finally {
            cs.restoreGraphicsState();
        }
    }

    // ── paths ────────────────────────────────────────────────────────────────
    private void paintPath(PDPageContentStream cs, OCDPath p) throws IOException {
        if (p.geometry() == null) return;
        boolean eo = p.geometry().isEvenOdd();

        // Gradient fill → re-emit a faithful PDF axial/radial shading clipped to the path,
        // then stroke on top if needed. (Solid fills take the plain path below.)
        if (p.hasGradient()) {
            paintGradient(cs, p);
            if (p.isStroked()) {
                int s = p.stroke();
                cs.setStrokingColor(r(s), g(s), b(s));
                cs.setLineWidth((float) Math.max(p.strokeWidth(), 0));
                cs.setLineCapStyle(p.cap());
                cs.setLineJoinStyle(p.join());
                if (p.miterLimit() > 0) cs.setMiterLimit((float) p.miterLimit());
                if (p.hasDash()) {
                    double[] d = p.dash();
                    float[] f = new float[d.length];
                    for (int i = 0; i < d.length; i++) f[i] = (float) d[i];
                    cs.setLineDashPattern(f, (float) p.dashPhase());
                }
                emitGeom(cs, p.geometry());
                cs.stroke();
            }
            return;
        }
        if (p.isStroked()) {
            int s = p.stroke();
            cs.setStrokingColor(r(s), g(s), b(s));
            cs.setLineWidth((float) Math.max(p.strokeWidth(), 0));
            cs.setLineCapStyle(p.cap());
            cs.setLineJoinStyle(p.join());
            if (p.miterLimit() > 0) cs.setMiterLimit((float) p.miterLimit());
            if (p.hasDash()) {
                double[] d = p.dash();
                float[] f = new float[d.length];
                for (int i = 0; i < d.length; i++) f[i] = (float) d[i];
                cs.setLineDashPattern(f, (float) p.dashPhase());
            }
        }
        if (p.isFilled()) { int f = p.fill(); cs.setNonStrokingColor(r(f), g(f), b(f)); }

        emitGeom(cs, p.geometry());
        if (p.isFilled() && p.isStroked()) { if (eo) cs.fillAndStrokeEvenOdd(); else cs.fillAndStroke(); }
        else if (p.isFilled())            { if (eo) cs.fillEvenOdd();         else cs.fill(); }
        else if (p.isStroked())           cs.stroke();
    }

    /** Fill a path with a re-emitted PDF axial/radial shading, clipped to the geometry. The
     *  shading is painted in its own space; the gradient→page matrix is applied as CTM so the
     *  ramp lands exactly where it did in the source. */
    private void paintGradient(PDPageContentStream cs, OCDPath p) throws IOException {
        OCDGradient grad = p.fillGradient();
        PDShading shading = buildShading(grad);
        cs.saveGraphicsState();
        int a0 = (grad.colors()[0] >>> 24) & 0xFF;        // shadings carry no per-stop alpha → ca
        if (a0 < 255) {
            PDExtendedGraphicsState egs = new PDExtendedGraphicsState();
            egs.setNonStrokingAlphaConstant(a0 / 255f);
            cs.setGraphicsStateParameters(egs);
        }
        emitGeom(cs, p.geometry());
        if (p.geometry().isEvenOdd()) cs.clipEvenOdd(); else cs.clip();
        JxTransform t = grad.transform();
        cs.transform(new Matrix((float) t.a(), (float) t.b(), (float) t.c(),
                                (float) t.d(), (float) t.tx(), (float) t.ty()));
        cs.shadingFill(shading);
        cs.restoreGraphicsState();
    }

    /** Build a DeviceRGB axial (type 2) / radial (type 3) shading from an OCDGradient. */
    private static PDShading buildShading(OCDGradient g) throws IOException {
        COSDictionary d = new COSDictionary();
        d.setInt(COSName.SHADING_TYPE, g.isLinear() ? 2 : 3);
        d.setItem(COSName.COLORSPACE, COSName.DEVICERGB);
        d.setItem(COSName.COORDS, floats(g.coords()));
        d.setItem(COSName.DOMAIN, floats(new double[]{0, 1}));
        d.setItem(COSName.FUNCTION, buildFunction(g));
        COSArray ext = new COSArray();
        ext.add(COSBoolean.getBoolean(g.extend0()));
        ext.add(COSBoolean.getBoolean(g.extend1()));
        d.setItem(COSName.EXTEND, ext);
        return PDShading.create(d);
    }

    /** A piecewise-linear stitching function (type 3 over type-2 segments) that reproduces the
     *  gradient's colour stops exactly — the inverse of how the importer sampled them. */
    private static COSDictionary buildFunction(OCDGradient g) {
        float[] off = g.offsets();
        int[]   col = g.colors();
        int n = off.length;
        COSArray funcs = new COSArray(), bounds = new COSArray(), encode = new COSArray();
        for (int i = 0; i < n - 1; i++) {
            COSDictionary seg = new COSDictionary();
            seg.setInt(COSName.FUNCTION_TYPE, 2);
            seg.setItem(COSName.DOMAIN, floats(new double[]{0, 1}));
            seg.setItem(COSName.C0, rgbArr(col[i]));
            seg.setItem(COSName.C1, rgbArr(col[i + 1]));
            seg.setItem(COSName.N, new COSFloat(1f));
            funcs.add(seg);
            encode.add(new COSFloat(0f));
            encode.add(new COSFloat(1f));
        }
        for (int i = 1; i < n - 1; i++) bounds.add(new COSFloat(off[i]));
        COSDictionary d = new COSDictionary();
        d.setInt(COSName.FUNCTION_TYPE, 3);
        d.setItem(COSName.DOMAIN, floats(new double[]{0, 1}));
        d.setItem(COSName.FUNCTIONS, funcs);
        d.setItem(COSName.BOUNDS, bounds);
        d.setItem(COSName.ENCODE, encode);
        return d;
    }

    private static COSArray floats(double[] v) {
        COSArray a = new COSArray();
        for (double x : v) a.add(new COSFloat((float) x));
        return a;
    }

    private static COSArray rgbArr(int argb) {
        COSArray a = new COSArray();
        a.add(new COSFloat(((argb >> 16) & 0xFF) / 255f));
        a.add(new COSFloat(((argb >> 8)  & 0xFF) / 255f));
        a.add(new COSFloat(( argb        & 0xFF) / 255f));
        return a;
    }

    // ── text: filled glyph outlines (pixel-exact, not selectable) ────────────
    private void paintTextOutline(PDPageContentStream cs, OCDText t, OCDDocument doc) throws IOException {
        if (t.isInvisible() || t.glyphs().isEmpty()) return;
        OCDFont font = doc.findFont(t.fontId());
        if (font == null) return;
        boolean doStroke = t.hasStrokePaint();
        boolean doFill   = t.hasFill() || !doStroke;
        int fill = t.fill();
        cs.setNonStrokingColor(r(fill), g(fill), b(fill));
        double fs = t.fontSize();
        if (doStroke) setGlyphStroke(cs, t, fs);   // line params in em space (glyph outline drawn scaled by fs)
        AffineTransform base = t.transform().awt();
        for (OCDText.Glyph gl : t.glyphs()) {
            OCDGlyph fg = font.glyph(gl.gid());
            if (fg == null || fg.outline() == null || fg.isSpace()) continue;
            AffineTransform at = new AffineTransform(base);
            at.translate(gl.x(), 0);
            at.scale(fs, fs);
            paintGlyph(cs, fg.outline(), at, doFill, doStroke);
        }
    }

    /** Emit one glyph outline under {@code at} and paint it by fill / stroke / both. */
    private void paintGlyph(PDPageContentStream cs, JxPath outline, AffineTransform at, boolean doFill, boolean doStroke) throws IOException {
        cs.saveGraphicsState();
        cs.transform(new Matrix(at));
        emitGeom(cs, outline);
        if (doFill && doStroke) cs.fillAndStroke();
        else if (doStroke)      cs.stroke();
        else                    cs.fill();
        cs.restoreGraphicsState();
    }

    /** Stroke graphics state for an em-scaled glyph outline: page-space width/dash divided by {@code fs}. */
    private void setGlyphStroke(PDPageContentStream cs, OCDText t, double fs) throws IOException {
        int s = t.stroke();
        cs.setStrokingColor(r(s), g(s), b(s));
        cs.setLineWidth((float) Math.max(t.strokeWidth() / fs, 0));
        cs.setLineCapStyle(t.cap());
        cs.setLineJoinStyle(t.join());
        if (t.miterLimit() > 0) cs.setMiterLimit((float) t.miterLimit());
        if (t.hasDash()) cs.setLineDashPattern(scaleDash(t.dash(), 1.0 / fs), (float) (t.dashPhase() / fs));
    }

    private static float[] scaleDash(double[] dash, double k) {
        float[] f = new float[dash.length];
        for (int i = 0; i < dash.length; i++) f[i] = (float) (dash[i] * k);
        return f;
    }

    /** Stroke graphics state for {@code showText}: the line width is user-space (the text matrix scales the
     *  glyph by font size, but the stroke width is the general line width), so no {@code /fs} division. */
    private void setTextStroke(PDPageContentStream cs, OCDText t) throws IOException {
        int s = t.stroke();
        cs.setStrokingColor(r(s), g(s), b(s));
        cs.setLineWidth((float) Math.max(t.strokeWidth(), 0));
        cs.setLineCapStyle(t.cap());
        cs.setLineJoinStyle(t.join());
        if (t.miterLimit() > 0) cs.setMiterLimit((float) t.miterLimit());
        if (t.hasDash()) cs.setLineDashPattern(scaleDash(t.dash(), 1.0), (float) t.dashPhase());
    }

    // ── text: faithful VISIBLE real text via the embedded font ───────────────
    // The OTF cmap now maps codepoint→gid correctly, so we render each glyph by
    // the codepoint that maps to its gid (reverse of the font cmap — reliable,
    // unlike the source ToUnicode), giving real selectable text with exact
    // shapes. Glyphs absent from the cmap fall back to an exact outline fill.
    private void paintTextEmbedded(PDPageContentStream cs, OCDText t, OCDDocument doc) throws IOException {
        if (t.isInvisible() || t.glyphs().isEmpty()) return;
        OCDFont font = doc.findFont(t.fontId());
        if (font == null) return;
        PDFont pdFont = fonts.computeIfAbsent(t.fontId(), k -> loadFont(font));
        if (pdFont == null) { paintTextOutline(cs, t, doc); return; }
        Map<Integer, Integer> rev = font.reverseCmap();   // gid → encodable codepoint (cached)

        int fill = t.fill();
        float cr = r(fill), cg = g(fill), cb = b(fill);
        double fs = t.fontSize();
        boolean doStroke = t.hasStrokePaint();
        boolean doFill   = t.hasFill() || !doStroke;
        RenderingMode rm = !doStroke ? RenderingMode.FILL
                : (doFill ? RenderingMode.FILL_STROKE : RenderingMode.STROKE);
        AffineTransform base = t.transform().awt();
        boolean inText = false;
        for (OCDText.Glyph gl : t.glyphs()) {
            Integer cp = rev.get(gl.gid());
            String s = (cp != null && cp >= 0x20) ? new String(Character.toChars(cp)) : null;
            boolean shown = false;
            if (s != null) {
                try {
                    if (!inText) {
                        if (doStroke) setTextStroke(cs, t);   // line params before BT; showText stroke width is user-space (not /fs)
                        cs.beginText(); cs.setRenderingMode(rm); cs.setFont(pdFont, (float) fs); cs.setNonStrokingColor(cr, cg, cb); inText = true;
                    }
                    AffineTransform at = new AffineTransform(base);
                    at.translate(gl.x(), 0);
                    cs.setTextMatrix(new Matrix(at));
                    cs.showText(s);
                    shown = true;
                } catch (RuntimeException ignore) { /* not encodable → outline below */ }
            }
            if (!shown) {
                if (inText) { cs.endText(); inText = false; }
                OCDGlyph fg = font.glyph(gl.gid());
                if (fg != null && fg.outline() != null && !fg.isSpace()) {
                    cs.setNonStrokingColor(cr, cg, cb);
                    if (doStroke) setGlyphStroke(cs, t, fs);   // fallback outline is em-scaled
                    AffineTransform at = new AffineTransform(base);
                    at.translate(gl.x(), 0);
                    at.scale(fs, fs);
                    paintGlyph(cs, fg.outline(), at, doFill, doStroke);
                }
            }
        }
        if (inText) cs.endText();
    }

    private PDFont loadFont(OCDFont font) {
        try {
            byte[] otf = JxFont.toOtf(font);
            if (otf == null || otf.length == 0) return null;
            return PDType0Font.load(pdf, new ByteArrayInputStream(otf), true);   // embedSubset → ToUnicode auto
        } catch (Exception e) {
            JxLog.debug(PdfWriter.class, "font embed failed \u2192 outline fallback: " + font.name(), e);
            return null;   // fall back to outline rendering
        }
    }

    // ── images ────────────────────────────────────────────────────────────────
    private void paintImage(PDPageContentStream cs, OCDImage im, OCDDocument doc) throws IOException {
        String ref = im.resourceRef();
        if (ref == null) return;
        PDImageXObject img = images.get(ref);
        if (img == null) {
            byte[] bytes = doc.image(ref);
            if (bytes == null) return;
            img = PDImageXObject.createFromByteArray(pdf, bytes, ref);
            images.put(ref, img);
        }
        cs.drawImage(img, new Matrix(im.transform().awt()));   // unit square → page
    }

    // ── per-node alpha (fill/stroke) + blend via ExtGState ───────────────────
    private void applyState(PDPageContentStream cs, OCDNode n) throws IOException {
        float na = n.alpha();
        float fillA = na, strokeA = na;
        if (n instanceof OCDPath p) {
            if (p.isFilled())  fillA   = na * a(p.fill());
            if (p.isStroked()) strokeA = na * a(p.stroke());
        } else if (n instanceof OCDText t) {
            fillA = na * a(t.fill());
            if (t.hasStrokePaint()) strokeA = na * a(t.stroke());
        }
        String blend = n.blend();
        BlendMode bm = (blend != null && !blend.isEmpty()) ? BLEND.get(blend) : null;
        if (fillA < 1f || strokeA < 1f || bm != null) {
            PDExtendedGraphicsState gs = new PDExtendedGraphicsState();
            gs.setNonStrokingAlphaConstant(fillA);
            gs.setStrokingAlphaConstant(strokeA);
            if (bm != null) gs.setBlendMode(bm);
            cs.setGraphicsStateParameters(gs);
        }
    }

    private static final Map<String, BlendMode> BLEND = new HashMap<>();
    static {
        BLEND.put("Normal", BlendMode.NORMAL);          BLEND.put("Multiply", BlendMode.MULTIPLY);
        BLEND.put("Screen", BlendMode.SCREEN);          BLEND.put("Overlay", BlendMode.OVERLAY);
        BLEND.put("Darken", BlendMode.DARKEN);          BLEND.put("Lighten", BlendMode.LIGHTEN);
        BLEND.put("ColorDodge", BlendMode.COLOR_DODGE); BLEND.put("ColorBurn", BlendMode.COLOR_BURN);
        BLEND.put("HardLight", BlendMode.HARD_LIGHT);   BLEND.put("SoftLight", BlendMode.SOFT_LIGHT);
        BLEND.put("Difference", BlendMode.DIFFERENCE);  BLEND.put("Exclusion", BlendMode.EXCLUSION);
        BLEND.put("Hue", BlendMode.HUE);                BLEND.put("Saturation", BlendMode.SATURATION);
        BLEND.put("Color", BlendMode.COLOR);            BLEND.put("Luminosity", BlendMode.LUMINOSITY);
    }

    // ── geometry emission (quad → cubic for TrueType glyph outlines) ─────────
    private static void emitGeom(PDPageContentStream cs, JxPath path) throws IOException {
        double[] c = new double[6];
        double cx = 0, cy = 0, sx = 0, sy = 0;
        for (PathIterator it = path.getPathIterator(null); !it.isDone(); it.next()) {
            switch (it.currentSegment(c)) {
                case PathIterator.SEG_MOVETO -> { cs.moveTo((float) c[0], (float) c[1]); cx = sx = c[0]; cy = sy = c[1]; }
                case PathIterator.SEG_LINETO -> { cs.lineTo((float) c[0], (float) c[1]); cx = c[0]; cy = c[1]; }
                case PathIterator.SEG_QUADTO -> {
                    double q1x = cx + 2.0 / 3 * (c[0] - cx), q1y = cy + 2.0 / 3 * (c[1] - cy);
                    double q2x = c[2] + 2.0 / 3 * (c[0] - c[2]), q2y = c[3] + 2.0 / 3 * (c[1] - c[3]);
                    cs.curveTo((float) q1x, (float) q1y, (float) q2x, (float) q2y, (float) c[2], (float) c[3]);
                    cx = c[2]; cy = c[3];
                }
                case PathIterator.SEG_CUBICTO -> {
                    cs.curveTo((float) c[0], (float) c[1], (float) c[2], (float) c[3], (float) c[4], (float) c[5]);
                    cx = c[4]; cy = c[5];
                }
                case PathIterator.SEG_CLOSE -> { cs.closePath(); cx = sx; cy = sy; }
                default -> { }
            }
        }
    }

    private static float r(int argb) { return ((argb >> 16) & 0xff) / 255f; }
    private static float g(int argb) { return ((argb >> 8) & 0xff) / 255f; }
    private static float b(int argb) { return (argb & 0xff) / 255f; }
    private static float a(int argb) { return ((argb >>> 24) & 0xff) / 255f; }

    // ── bookmarks: the heading structure → a navigable PDF outline ─────────────
    /** Build a document outline (bookmarks) from the default structure's headings, nested by level,
     *  reusing the same heading→page resolution as the EPUB nav. No-op when there is no heading
     *  structure; independent of the text mode. */
    private static void outline(PDDocument pdf, OCDDocument doc) {
        OCDStruct root = doc.structure();
        if (root == null) return;
        List<OCDStruct> heads = new ArrayList<>();
        EpubPackage.collectHeadings(root, heads);
        if (heads.isEmpty()) return;
        OCDIndex ix = OCDIndex.of(doc);
        int pages = pdf.getNumberOfPages();
        PDDocumentOutline outline = new PDDocumentOutline();
        Deque<Lvl> stack = new ArrayDeque<>();
        for (OCDStruct h : heads) {
            int lv = Math.max(1, h.level());
            PDOutlineItem item = new PDOutlineItem();
            item.setTitle(EpubPackage.label(h, ix));
            int pi = EpubPackage.firstPage(h);
            if (pi >= 0 && pi < pages) {
                PDPageFitWidthDestination d = new PDPageFitWidthDestination();
                d.setPage(pdf.getPage(pi));
                item.setDestination(d);
            }
            while (!stack.isEmpty() && stack.peek().level() >= lv) stack.pop();
            if (stack.isEmpty()) outline.addLast(item); else stack.peek().node().addLast(item);
            stack.push(new Lvl(lv, item));
        }
        outline.openNode();
        pdf.getDocumentCatalog().setDocumentOutline(outline);
    }
    private record Lvl(int level, PDOutlineItem node) {}

    /** Deterministic document identity: CreationDate from the clock authority and a trailer
     *  {@code /ID} derived from the model id — the same model saved twice is byte-identical
     *  (PDFBox would otherwise hash the wall clock into the {@code /ID}). */
    private static void stamp(PDDocument pdf, OCDDocument doc) {
        java.util.Calendar cal = java.util.Calendar.getInstance(java.util.TimeZone.getTimeZone("UTC"));
        cal.setTimeInMillis(sugarcube.jexter.core.JxClock.millis());
        pdf.getDocumentInformation().setCreationDate(cal);
        pdf.getDocumentInformation().setModificationDate(cal);
        try {
            byte[] h = java.security.MessageDigest.getInstance("MD5")
                    .digest(("jexter:" + doc.id()).getBytes(java.nio.charset.StandardCharsets.UTF_8));
            var id = new org.apache.pdfbox.cos.COSArray();
            id.add(new org.apache.pdfbox.cos.COSString(h));
            id.add(new org.apache.pdfbox.cos.COSString(h));
            pdf.getDocument().getTrailer().setItem(org.apache.pdfbox.cos.COSName.ID, id);
        } catch (java.security.NoSuchAlgorithmException ignore) {}   // MD5 is mandatory in every JRE
    }
}
