package sugarcube.jexter.ocd.analysis;

import sugarcube.jexter.ocd.model.IdStamper;
import sugarcube.jexter.ocd.model.OCDBreak;
import sugarcube.jexter.ocd.model.OCDDocument;
import sugarcube.jexter.ocd.model.OCDGraphic;
import sugarcube.jexter.ocd.model.OCDGroup;
import sugarcube.jexter.ocd.model.OCDNode;
import sugarcube.jexter.ocd.model.OCDPage;
import sugarcube.jexter.ocd.model.OCDParagraph;
import sugarcube.jexter.ocd.model.OCDStruct;
import sugarcube.jexter.ocd.model.OCDStructure;
import sugarcube.jexter.ocd.model.OCDText;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Cleans a page's content down to its essential, content-bearing nodes — the idempotent base every analysis
 * pass starts from, <b>without losing any structure already on the document</b>. It does not produce the final
 * canonical document (the rest of the pipeline does); it removes the non-painting noise so every pass reads the
 * same input. Four things, all fidelity-exact:
 *
 * <ul>
 *   <li><b>Keep inked runs intact</b> — a text run and its glyphs (including the positions of space glyphs) are
 *       preserved as the geometric evidence. Word and space reconstruction is a late, line-level pass, not this
 *       one, so the run boundary the PDF happened to emit is never trusted as a word boundary here.</li>
 *   <li><b>Drop whitespace-only runs</b> — a blank paints nothing; the word space it carried is rebuilt from the
 *       inter-run gap on read-out, except where it is the only space between two glued runs (then kept).</li>
 *   <li><b>Drop line-break tokens</b> — {@link OCDBreak}s paint nothing and are regenerated by restructuring.</li>
 *   <li><b>Splice render-neutral wrappers</b> — identity {@link OCDParagraph} / {@link OCDGraphic} wrappers are
 *       removed; render-bearing {@link OCDGroup}s (Form XObjects, transparency groups) are kept and recursed
 *       into.</li>
 * </ul>
 *
 * <p><b>Structure-preserving, not structure-clearing.</b> Cleaning is a pure change of representation, so it
 * must not break the structures whose refs point at the pre-clean nodes — above all the PDF/UA ground truth
 * ({@code pdf}). As it rebuilds each page it records, per spliced wrapper, the content nodes it unwrapped to,
 * mints any new ids through the single {@link IdStamper} authority, then rewrites every structure ref through
 * that map: a ref to a spliced wrapper becomes refs to its content nodes; a ref to a kept node is unchanged.
 * The logical shape of every structure is preserved. Re-running {@code clean} on an already-clean document is a
 * no-op.
 */
public final class Cleaner {

    private Cleaner() {}

    public static void clean(OCDDocument doc) {
        // pass 1 — rebuild each page's content, recording provenance (spliced wrapper id -> content nodes)
        List<Map<String, List<OCDNode>>> provByPage = new ArrayList<>(doc.pageCount());
        for (OCDPage p : doc.pages()) {
            Map<String, List<OCDNode>> prov = new LinkedHashMap<>();
            List<OCDNode> out = new ArrayList<>(p.content().size());
            for (OCDNode n : p.content()) clean(n, out, prov);
            p.content().clear();
            p.content().addAll(out);
            provByPage.add(prov);
        }

        // mint any new ids — single authority, continuing each per-(page,kind) sequence past the ids already
        // present, so an existing (possibly referenced) id is never disturbed.
        IdStamper.fill(doc);

        // pass 2 — rewrite every structure ref through old-id -> [new ids]; structures are preserved
        for (int pi = 0; pi < provByPage.size(); pi++) {
            Map<String, List<OCDNode>> prov = provByPage.get(pi);
            if (prov.isEmpty()) continue;
            Map<String, List<String>> remap = new HashMap<>();
            prov.forEach((oldId, objs) -> {
                List<String> ids = new ArrayList<>(objs.size());
                for (OCDNode o : objs) if (o.id() != null) ids.add(o.id());
                remap.put(oldId, ids);
            });
            for (OCDStructure st : doc.structures()) remap(st.root(), pi, remap);
        }
    }

    /** Append the cleaned form of {@code n} into {@code out}, recording in {@code prov} the content nodes a
     *  spliced wrapper unwrapped to (so its refs can be remapped). */
    private static void clean(OCDNode n, List<OCDNode> out, Map<String, List<OCDNode>> prov) {
        if (n instanceof OCDBreak) return;                       // line-break token: paints nothing
        if (n instanceof OCDText t) {                            // a run: strip its blanks (real spaces + prior
            t.glyphs().removeIf(OCDText.Glyph::isBlank);               // sentinels), then keep it only if ink remains
            if (!t.glyphs().isEmpty()) out.add(t);
            return;
        }
        if (isNeutralWrapper(n)) {                               // paragraph / graphic, no render effect → splice
            int from = out.size();
            for (OCDNode c : ((OCDGroup) n).children()) clean(c, out, prov);
            if (n.id() != null) prov.put(n.id(), new ArrayList<>(out.subList(from, out.size())));  // wrapper id -> its content
            return;
        }
        if (n instanceof OCDGroup g) {                          // render-bearing group → keep, recurse
            List<OCDNode> inner = new ArrayList<>(g.children().size());
            for (OCDNode c : g.children()) clean(c, inner, prov);   // child ids are page-unique → same prov map
            g.children().clear();
            g.children().addAll(inner);
            out.add(g);
            return;
        }
        out.add(n);                                             // path / image / media leaf → keep id
    }

    /** A paragraph/graphic wrapper that applies no rendering of its own — safe to splice away. */
    private static boolean isNeutralWrapper(OCDNode n) {
        return (n instanceof OCDParagraph || n instanceof OCDGraphic)
                && n.transform().isIdentity() && !n.hasClip() && n.alpha() >= 1f && !n.hasBlend();
    }

    /** Rewrite a structure subtree's refs on page {@code pi}: expand a spliced wrapper into its content nodes;
     *  leave a ref to a kept node untouched. */
    private static void remap(OCDStruct s, int pi, Map<String, List<String>> remap) {
        if (!s.refs().isEmpty()) {
            List<OCDStruct.Ref> old = new ArrayList<>(s.refs());
            s.refs().clear();
            for (OCDStruct.Ref r : old) {
                List<String> to = (r.page() == pi) ? remap.get(r.nodeId()) : null;
                if (to != null) for (String nid : to) s.addRef(pi, nid);
                else s.refs().add(r);
            }
        }
        for (OCDStruct c : s.children()) remap(c, pi, remap);
    }

}
